[workspace]
members = ["bouncer-bin", "bouncer-cli", "bouncer-config"]
resolver = "2"

[workspace.package]
version = "0.0.0"
license = "GPL-3.0"
publish = false
edition = "2021"
rust-version = "1.82.0"

[workspace.dependencies]
anyhow = "1.0.92"
thiserror = "1.0.67"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[profile.release]
lto = "thin"
